apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-boot-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: ab4ea5cfd675f4af4bb925aa9e7e3ec9-1311069641.us-east-1.elb.amazonaws.com
      http:
        paths:
          - path: /live
            pathType: Prefix
            backend:
              service:
                name: spring-boot-service
                port:
                  number: 80





